# Generated by Django 4.0.6 on 2022-07-27 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.TextField(choices=[('#FFFFFF', 'White'), ('#FF0000', 'Red'), ('#000000', 'Black'), ('#0086FF', 'Blue'), ('#04D61F', 'Green'), ('#FFFD00', 'Yellow'), ('#FF7F00', 'Orange'), ('#D100FF', 'Purple'), ('#845A0F', 'Brown')], default='#000000'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
