# Generated by Django 4.0.6 on 2022-07-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards', '0002_alter_card_font_color_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bg_color',
            field=models.TextField(choices=[('White', 'White'), ('Red', 'Red'), ('Black', 'Black'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Brown', 'Brown')], default='White'),
        ),
        migrations.AlterField(
            model_name='card',
            name='border_color',
            field=models.TextField(choices=[('White', 'White'), ('Red', 'Red'), ('Black', 'Black'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Brown', 'Brown')], default='Black'),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.TextField(choices=[('cormorant', 'Cormorant Unicase'), ('kaushan', 'Kaushan Script'), ('amatic', 'Amatic SC'), ('bungee', 'Bungee Shade'), ('righteous', 'Righteous'), ('julius', 'Julius Sans One'), ('roboto', 'Roboto'), ('spectral', 'Spectral'), ('dancing', 'Dancing Script')], default='roboto'),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.TextField(choices=[('White', 'White'), ('Red', 'Red'), ('Black', 'Black'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Brown', 'Brown')], default='Black'),
        ),
    ]
