# Generated by Django 4.0.6 on 2022-07-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards', '0003_alter_card_bg_color_alter_card_border_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bg_color',
            field=models.TextField(choices=[('White', 'white'), ('Red', 'red'), ('Black', 'black'), ('Blue', 'blue'), ('Green', 'green'), ('Yellow', 'yellow'), ('Orange', 'orange'), ('Purple', 'purple'), ('Brown', 'brown')], default='White'),
        ),
        migrations.AlterField(
            model_name='card',
            name='border_color',
            field=models.TextField(choices=[('White', 'white'), ('Red', 'red'), ('Black', 'black'), ('Blue', 'blue'), ('Green', 'green'), ('Yellow', 'yellow'), ('Orange', 'orange'), ('Purple', 'purple'), ('Brown', 'brown')], default='Black'),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.TextField(choices=[('White', 'white'), ('Red', 'red'), ('Black', 'black'), ('Blue', 'blue'), ('Green', 'green'), ('Yellow', 'yellow'), ('Orange', 'orange'), ('Purple', 'purple'), ('Brown', 'brown')], default='Black'),
        ),
    ]
