# Generated by Django 4.0.6 on 2022-08-05 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecards', '0012_alter_follow_following_follow_unique_following'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_following',
        ),
    ]
